package ljubisa

import ljubisa.model.*;
import java.util.Set
import java.util.List
import java.time.LocalDate
import javax.swing.JTextArea

rule "print 1"
agenda-group "hronicni"
salience  301
	when	
		$txt : JTextArea(  )
	then
		$txt.setText($txt.getText() + "Spisak pacijenata sa mogucom hronicnom upalom krajnika: \n");
end

rule "Spisak pacijenata sa mogucom hronicnom upalom krajnika"
agenda-group "hronicni"
salience 300
    when
    	$text : JTextArea(  )
    	$pac : Pacijent($ter : terapije) and
    	$brr : Number(intValue > 5) from accumulate(
    	$trr : Terapija($bolest:bolest) from $ter and 
    	Bolest(naziv == "upalaKrajnika") from $bolest, count($trr))
    then
    	$text.setText($text.getText() + "	" + $pac + "\n");
end

rule "print 2"
agenda-group "hronicni"
salience  299
	when	
		$txt : JTextArea(  )
	then
		$txt.setText($txt.getText() + "Spisak pacijenata sa mogucom hronicnom sinusnom infekcijom: \n");
end

rule "Spisak pacijenata sa mogucom hronicnom sinusnom infekcijom"
agenda-group "hronicni"
salience  298
    when
    	$txt : JTextArea(  )
        $pac : Pacijent($ter : terapije) and
    	$brr : Number(intValue > 5) from accumulate(
    	$trr : Terapija($bol : bolest) from $ter and 
    	Bolest(naziv == "sinusnaInfekcija") from $bol, count($trr))
    then
        $txt.setText($txt.getText() + "	"+$pac + "\n");
end

rule "print 3"
agenda-group "hronicni"
salience  297
	when	
		$txt : JTextArea(  )
	then
		$txt.setText($txt.getText() + "Spisak pacijenata sa mogucom hronicnom hipertenzijom: \n");
   		$txt.validate();
 		$txt.repaint();
end

rule "Spisak pacijenata sa mogucmom hronicnom hipertenzijom"
agenda-group "hronicni"
salience 296
    when
   		$txt : JTextArea(  )
        $pac : Pacijent($ter : terapije) and
    	$brr : Number(intValue > 5) from accumulate (
    	$trr : Terapija($bol : bolest) from $ter and 
    	Bolest(naziv == "hipertenzija") from $bol, count($trr))
    then
        $txt.setText($txt.getText() + "	" + $pac + "\n");

end

rule "print 4"
agenda-group "hronicni"
salience  295
	when	
		$txt : JTextArea(  )
	then
		$txt.setText($txt.getText() + "Spisak pacijenata sa mogucim hronicnim dijabetesom: \n");
end

rule "Spisak pacijenata sa mogucmom hronicnom dijabetesom"
agenda-group "hronicni"
salience  294
    when
    	$txt : JTextArea(  )
        $pac : Pacijent($ter:terapije) and
    	$brr : Number(intValue>5) from accumulate(
    	$pt : Terapija($bolest:bolest) from $ter and 
    	Bolest(naziv == "dijabetes") from $bolest, count($pt))
    then
        $txt.setText($txt.getText() + "	" + $pac + "\n");
end

rule "print 5"
agenda-group "hronicni"
salience  293
	when	
		$txt : JTextArea(  )
	then
		$txt.setText($txt.getText() + "Spisak pacijenata sa mogucom hronicnom bubreznom bolesti: \n");
end

rule "Spisak acijenata sa mogucom hronicnom bubreznom bolesti"
agenda-group "hronicni"
salience  292
    when
    	$txt : JTextArea(  )
        $pac : Pacijent($ter : terapije) and
    	$brr : Number(intValue > 5) from accumulate(
    	$trr : Terapija($bol : bolest) from $ter and 
    	Bolest(naziv=="hronicnaBubreznaBolest") from $bol, count($trr))
    then
        $txt.setText($txt.getText() + "	" + $pac + "\n");
end

rule "print 6"
agenda-group "hronicni"
salience  292
	when	
		$txt : JTextArea(  )
	then
		$txt.setText($txt.getText() + "Spisak pacijenata sa mogucom hronicnom akutnom bubreznom povredom: \n");
end

rule "Spisak pacijenata sa mogucom hronicnom akutnom bubreznom povredom"
salience  291
agenda-group "hronicni"
    when
    	$txt : JTextArea(  )
        $pac : Pacijent($ter : terapije) and
    	$brr : Number(intValue > 5) from accumulate(
    	$trr : Terapija($bol : bolest) from $ter and 
    	Bolest(naziv == "akutnaBubreznaBolest") from $bol, count($trr))
    then
        $txt.setText($txt.getText() + "	" + $pac + "\n");
end


rule "Spisak pacijenata sa oslabljenim imunitetom print"
salience  301
agenda-group "osabljeniImunitet"
	when 
		$txt : JTextArea(  )
	then 
		$txt.setText($txt.getText() + "Spisak pacijenata sa oslabljenim imunitetom: \n");
end

rule "Spisak pacijenata sa oslabljenim imunitetom"
salience  300
agenda-group "osabljeniImunitet"
	when
		$txt : JTextArea(  )
		$pac : Pacijent($ter : terapije)
		$lon : Long() from accumulate(
		$trr : Terapija($pre : lekovi, datum.isAfter(LocalDate.now().minusMonths(12))) from $ter and
		$lis : List(size > 0) from collect ($lek : Lek(tipoviLekova.toString =="ANTIHISTAMIN") from $pre), count($trr))
		$al1 : Long() from accumulate(
		$al2 : Terapija($pre2 : lekovi, datum.isAfter(LocalDate.now().minusMonths(12))) 
		from $ter, count($al2))
		eval($lon == $al1)
		eval($lon > 10)
		$set : Set(size > 1) from accumulate( 
		$te2 : Terapija($bolest1 : bolest, datum.isAfter(LocalDate.now().minusMonths(12))) from $ter and
		bol : Bolest(  ) from $bolest1, collectSet(bol))		 	
	then
		$txt.setText($txt.getText() + "	" + $pac + "\n");
end 

rule "spisak mogucih zavisnika print"
salience 301
agenda-group "moguciZavisnici"
	when 
		$txt : JTextArea(  )
	then 
		$txt.setText($txt.getText() + "Spisak mogucih zavisnika: \n");
end

rule "spisak mogucih zavisnika"
salience 300
agenda-group "moguciZavisnici"
	when 
		$txt : JTextArea(  )
		$pac : Pacijent($ter : terapije)
		$lon : Long(intValue > 5) from accumulate (
		$trt : Terapija($pre : lekovi, datum.isAfter(LocalDate.now().minusMonths(6)))
		from $ter and
		$lista : List(size>0) from collect ($lek:Lek(tipoviLekova.toString == "ANTIDEPRESIV") from $pre), count($trt)) 
		$setLekari : Set(size > 2) from accumulate( 
		$ptL : Terapija($lekar : lekar, datum.isAfter(LocalDate.now().minusMonths(6))) from $ter and
		o1:Osoba() from $lekar, collectSet(o1))
	then
		$txt.setText($txt.getText() + "	" + $pac + "\n");
end

rule "clear ta hronicna"
agenda-group "hronicni"
salience 1000
enabled true
	when	
		$txt : JTextArea(  )
	then	
		$txt.setText("");			
end

rule "remove text from session hronicna"
agenda-group "hronicni"
salience -1000
enabled true
	when
		 $txt : JTextArea(  )
	then
		 delete($txt);
end

rule "clear text OslabljenImunitet"
agenda-group "osabljeniImunitet"
salience 1000
enabled true
	when	
		$txt : JTextArea(  )
	then	
		$txt.setText("");		
end

rule "remove text from session OslabljenImunitet"
agenda-group "osabljeniImunitet"
salience -1000
enabled true
	when
		 $txt : JTextArea(  )
	then
		 delete($txt);
end

rule "clear text zavisnici"
agenda-group "moguciZavisnici"
salience 1000
enabled true
	when	
		$txt : JTextArea(  )
	then	
		$txt.setText("");			
end

rule "remove text from session zavisnici"
agenda-group "moguciZavisnici"
salience -1000
enabled true
	when
		 $txt : JTextArea(  )
	then
		 delete($txt);
end