package ljubisa

import ljubisa.model.*;
import ljubisa.cds.*;
import java.util.Set
import java.util.List
import javax.swing.JTextArea;
import java.lang.Thread

rule "Ubrzani srcani ritam "
    when
    	$text:JTextArea(  )
        $num:Number(intValue > 25) from accumulate ($hb:OtkucajSrca() over window:length(26), count($hb)) 
    then
        $text.setText($text.getText()+"UBRZANI SRCANI RITAM\n u poslednih 10 secundi zabelezeno vishe od 25 otkucaja srca  \n");
        insert(new UbrzanoKucanjeSrca());
end

rule "zaustavi tread"
enabled false
salience -1001
    when
    	$tr:Thread(  )
        not(OtkucajSrca() over window:time(10s))
    then
        $tr.stop();
end   

rule "zaustavi monitoring TextArea"
enabled true
salience -1100
    when
    	$text:JTextArea(  )
        not(OtkucajSrca() over window:time(10s))
    then
    	$text.setText($text.getText()+"\nHALT, zaustavi monitoring");
        drools.halt();
        
end   

rule	"suma kolicine mokrenja u posednjih 12 sati manja od 100 ml"
enabled false
	when
		$text:JTextArea(  )
		$num:Number(intValue<100) from accumulate(
		$mo:KolicinaMokrenja($ko:kolicinaMililitri) over window:time(12h), sum($ko))
	then
		insert(new UkupnaKolicinaMokrenja());
		$text.setText($text.getText()+"\n");
end

rule	"suma kolicine mokrenja u posednjih 12 sati manja od 100 mlTWEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEESTTTTTTTT"
	when
		$text:JTextArea(  )
		$num:Number(intValue>=100) from accumulate(
		$mo:KolicinaMokrenja($ko:kolicinaMililitri) over window:time(12h), sum($ko))
	then
		insert(new UkupnaKolicinaMokrenja());
end

rule 	"u poslednjih 10 sekundi zabelezeno vishe od 10 otkucaja srca"
	when
		Number(intValue >10) from accumulate(
		$hb:OtkucajSrca() over window:length(11),count($hb))
	then
		insert(new ViseOdDesetOtkucajaSrca());
end

rule	"pacijent boluje od hronicne bubrezne bolesti"
	when 
		$pac:Pacijent($ter:terapije)
		$li:List(size>0) from collect ($pt:Terapija(bolest.naziv =="hronicnaBubreznaBolest") from $ter) 

	then
		insert(new HronicnaBubreznaBolest());
end	


rule "Potrebna dijaliza"
salience -1
	when 
		$text:JTextArea(  )
		HronicnaBubreznaBolest()
		ViseOdDesetOtkucajaSrca()
		not(UkupnaKolicinaMokrenja())
	then
		$text.setText($text.getText()+ "HITNO POTREBNA DIJALIZA  \n");
		insert(new HitnaDijaliza());
end

rule "Nivo kisonika ukrvi pacijenta je manja od 70 mmHg"
	when
		Disanje($num:kiseonik<70) 
	then
		insert(new NizakNivoKiseonika());
		
end

rule "rast kisonika"
	when 
		$d1:Disanje($prethodni:kiseonik)
		$d2:Disanje(this != $d1, this after $d1, kiseonik > $prethodni) 
	then
		insert(new NivoKiseonikaRaste());
end

rule "problem sa kiseonikom"
salience -1
	when
		$text:JTextArea(  )
		not(NivoKiseonikaRaste() over window:time(15m)) 
		NizakNivoKiseonika()
	then
		$text.setText($text.getText()+"PROBLEM SA KISEONIKOM \n");
		insert(new NedostatakKiseonika());
end