package ljubisa

import ljubisa.model.*;
import java.util.Set
import java.util.List
import java.time.LocalDate
import javax.swing.JTextArea

rule "print 1"
agenda-group "hronicni"
salience  301
	when	
		$text:JTextArea(  )
	then
		$text.setText($text.getText()+"Spisak pacijenata sa mogucom hronicnom upalom krajnika: \n");
end

rule "Spisak pacijenata sa mogucom hronicnom upalom krajnika"
agenda-group "hronicni"
salience 300
    when
    	$text:JTextArea(  )
    	$pac:Pacijent($ter:terapije) and
    	$num:Number(intValue>5) from accumulate(
    	$pt:Terapija($bolest:bolest) from $ter and 
    	Bolest(naziv=="upalaKrajnika") from $bolest, count($pt))
    then
    	$text.setText($text.getText()+"	"+$pac+"\n");
end

rule "print 2"
agenda-group "hronicni"
salience  299
	when	
		$text:JTextArea(  )
	then
		$text.setText($text.getText()+"Spisak pacijenata sa mogucom hronicnom sinusnom infekcijom: \n");
end

rule "Spisak pacijenata sa mogucom hronicnom sinusnom infekcijom"
agenda-group "hronicni"
salience  298
    when
    	$text:JTextArea(  )
        $pac:Pacijent($ter:terapije) and
    	$num:Number(intValue>5) from accumulate(
    	$pt:Terapija($bolest:bolest) from $ter and 
    	Bolest(naziv=="sinusnaInfekcija") from $bolest, count($pt))
    then
        $text.setText($text.getText()+"	"+$pac+"\n");
end

rule "print 3"
agenda-group "hronicni"
salience  297
	when	
		$text:JTextArea(  )
	then
		$text.setText($text.getText()+"Spisak pacijenata sa mogucom hronicnom hipertenzijom: \n");
   		$text.validate();
 		$text.repaint();
end

rule "Spisak pacijenata sa mogucmom hronicnom hipertenzijom"
agenda-group "hronicni"
salience 296
    when
   		$text:JTextArea(  )
        $pac:Pacijent($ter:terapije) and
    	$num:Number(intValue>5) from accumulate (
    	$pt:Terapija($bolest:bolest) from $ter and 
    	Bolest(naziv=="hipertenzija") from $bolest, count($pt))
    then
        $text.setText($text.getText()+"	"+$pac+"\n");

end

rule "print 4"
agenda-group "hronicni"
salience  295
	when	
		$text:JTextArea(  )
	then
		$text.setText($text.getText()+"Spisak pacijenata sa mogucim hronicnim dijabetesom: \n");
end

rule "Spisak pacijenata sa mogucmom hronicnom dijabetesom"
agenda-group "hronicni"
salience  294
    when
    	$text:JTextArea(  )
        $pac:Pacijent($ter:terapije) and
    	$num:Number(intValue>5) from accumulate(
    	$pt:Terapija($bolest:bolest) from $ter and 
    	Bolest(naziv=="dijabetes") from $bolest, count($pt))
    then
        $text.setText($text.getText()+"	"+$pac+"\n");
end

rule "print 5"
agenda-group "hronicni"
salience  293
	when	
		$text:JTextArea(  )
	then
		$text.setText($text.getText()+"Spisak pacijenata sa mogucom hronicnom bubreznom bolesti: \n");
end

rule "Spisak acijenata sa mogucom hronicnom bubreznom bolesti"
agenda-group "hronicni"
salience  292
    when
    	$text:JTextArea(  )
        $pac:Pacijent($ter:terapije) and
    	$num:Number(intValue >5) from accumulate(
    	$pt:Terapija($bolest:bolest) from $ter and 
    	Bolest(naziv=="hronicnaBubreznaBolest") from $bolest, count($pt))
    then
        $text.setText($text.getText()+"	"+$pac+"\n");
end

rule "print 6"
agenda-group "hronicni"
salience  292
	when	
		$text:JTextArea(  )
	then
		$text.setText($text.getText()+"Spisak pacijenata sa mogucom hronicnom akutnom bubreznom povredom: \n");
end

rule "Spisak pacijenata sa mogucom hronicnom akutnom bubreznom povredom"
salience  291
agenda-group "hronicni"
    when
    	$text:JTextArea(  )
        $pac:Pacijent($ter: terapije) and
    	$num:Number(intValue>5) from accumulate(
    	$pt:Terapija($bolest:bolest) from $ter and 
    	Bolest(naziv=="akutnaBubreznaBolest") from $bolest, count($pt))
    then
        $text.setText($text.getText()+"	"+$pac+"\n");
end


rule "Spisak pacijenata sa oslabljenim imunitetom print"
salience  301
agenda-group "osabljeniImunitet"
	when 
		$text:JTextArea(  )
	then 
		$text.setText($text.getText()+"Spisak pacijenata sa oslabljenim imunitetom: \n");
end

rule "Spisak pacijenata sa oslabljenim imunitetom"
salience  300
agenda-group "osabljeniImunitet"
	when
		$text:JTextArea(  )
		$pac:Pacijent($ter:terapije)
		$l:Long() from accumulate(
		$pt:Terapija($pre:lekovi, datum.isAfter(LocalDate.now().minusMonths(12))) from $ter and
		$lista:List(size>0) from collect ($lek:Lek(tipoviLekova.toString =="ANTIHISTAMIN") from $pre), count($pt))
		$lAll:Long() from accumulate(
		$ptAll:Terapija($pre2:lekovi, datum.isAfter(LocalDate.now().minusMonths(12))) 
		from $ter, count($ptAll))
		eval($l==$lAll)
		eval($l>10)
		$setS:Set(size>1) from accumulate( 
		$ptL:Terapija($bolest1:bolest,datum.isAfter(LocalDate.now().minusMonths(12))) from $ter and
		b1: Bolest(  ) from $bolest1,collectSet(b1))		 	
	then
		$text.setText($text.getText()+ "	"+$pac+"\n");
end 

rule "spisak mogucih zavisnika print"
salience 301
agenda-group "moguciZavisnici"
	when 
		$text:JTextArea(  )
	then 
		$text.setText($text.getText()+"Spisak mogucih zavisnika: \n");
end

rule "spisak mogucih zavisnika"
salience 300
agenda-group "moguciZavisnici"
	when 
		$text:JTextArea(  )
		$pac:Pacijent($ter:terapije)
		$l:Long(intValue>5) from accumulate(
		$pt:Terapija($pre:lekovi,datum.isAfter(LocalDate.now().minusMonths(6)))
		from $ter and
		$lista:List(size>0) from collect ($lek:Lek(tipoviLekova.toString=="ANTIDEPRESIV") from $pre),count($pt)) 
		$setLekari:Set(size>2) from accumulate( 
		$ptL:Terapija($lekar:lekar,
		datum.isAfter(LocalDate.now().minusMonths(6))) from $ter and
		o1:Osoba() from $lekar, collectSet(o1))
	then
		$text.setText($text.getText()+ "	"+$pac+"\n");
end

rule "clear ta hronicna"
agenda-group "hronicni"
salience 1000
enabled true
	when	
		$text:JTextArea(  )
	then	
		$text.setText("");			
end

rule "remove text from session hronicna"
agenda-group "hronicni"
salience -1000
enabled true
	when
		 $text:JTextArea(  )
	then
		 delete($text);
end

rule "clear text OslabljenImunitet"
agenda-group "osabljeniImunitet"
salience 1000
enabled true
	when	
		$text:JTextArea(  )
	then	
		$text.setText("");		
end

rule "remove text from session OslabljenImunitet"
agenda-group "osabljeniImunitet"
salience -1000
enabled true
	when
		 $text:JTextArea(  )
	then
		 delete($text);
end

rule "clear text zavisnici"
agenda-group "moguciZavisnici"
salience 1000
enabled true
	when	
		$text:JTextArea(  )
	then	
		$text.setText("");			
end

rule "remove text from session zavisnici"
agenda-group "moguciZavisnici"
salience -1000
enabled true
	when
		 $text:JTextArea(  )
	then
		 delete($text);
end