package ljubisa

import ljubisa.model.*;
import java.util.Set
import java.util.List
import java.time.LocalDate
global Bolest dijabetes;
global Bolest hipertenzija;

rule "dijabetes moze biti"
agenda-group "druga"
salience 100 
    when
        $pre : Pregled($svi : sviSimptomi, $pot : potencijalneBolesti) and
        $stt : Set() from collect ($svi2 : SviSimptomi( 
        	this==SviSimptomi.CESTO_URINIRANJE ||
        	this==SviSimptomi.GUBITAK_TESENE_TEZINE ||
        	this==SviSimptomi.UMOR ||
        	this==SviSimptomi.MUCNINA_I_POVRACANJE
        )from $svi) and
        eval($stt.size() > 3)
        $dajMiBolest : PotencijalnaBolest(nazivBolesti == "dijabetes") from $pot 
    then
		$dajMiBolest.setSansa($stt.size()/4.0);
end

rule "hipertenzija moze biti"
agenda-group "druga"
salience 90
    when
        $pre : Pregled($pac : pacijent, $pot : potencijalneBolesti)
		$paa : Pacijent(this == $pac, $ter : terapije) from $pac
		$lis : List(size > 9) from collect (
		$trr : Terapija(visokPritisak == true, barDesetPutaVisokPritisaDoSestMeseci()) from $ter) 
		$pob : PotencijalnaBolest(nazivBolesti == "hipertenzija") from $pot 	
    then
		$pob.setSansa(1);
end