package ljubisa.model;

public enum SpecificniSimptomi {
	OPORAVLJA_SE_OD_OPERACIJE,
	POVISENA_TEMPERATURA_U_POSLEDNJIH_14_DANA,
	BOLUJE_OD_DIJABETESA,
	BOLUJE_OD_HIPERTENZIJE_DUZE_OD_6_MESECI,
	PREPISANI_ANTIBIOTICI_U_POSLEDNIH_21_DAN
}
