package ljubisa.model;

public enum SviSimptomi {
	KASALJ, GLAVOBOLJA, CURENJE_IZ_NOSA, BOL_U_GRLU, KIJANJE,
	BOL_KOJI_SE_SIRI_OD_USIJU, TEMPERATURA_IZMEDJU_40_I_41,
	GUBITAK_APETITA, TEMPERATURA_VECA_OD_38, UMOR, GUSENJE,
	BOLOVANJE_OD_PREHLADE_ILI_GROZNICE_U_PROTEKLIH_60_DANA,
	OTICANJE_OKO_OCIJU, CESTO_URINIRANJE, BOL_U_GRUDIMA,
	U_POSLEDNJIH_6_MESECI_ZABELEZEN_BAR_10_SLUCAJEVA_U_KOJEM_PACIJENT_IMA_VISOK_PRITISAK,
	DIJAREJA, MUCNINA_I_POVRACANJE, NOCTURIA, OTOCI_NOGU_I_ZGLOBOVA,
	DRHTAVICA, ZUTI_SEKRET_IZ_NOSA, GUBITAK_TESENE_TEZINE, 
}
